# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: 2859f602-9df2-47ec-9118-92f29afebf73
  namespace: 2859f602-9df2-47ec-9118-92f29afebf73
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: true
    instanceType: t3.micro
    disableIngressRules: false
    allowedCIDRBlocks:
      - 127.0.0.1/32
